#' Save print-and-play file of Dotaro Deck
#'
#' `save_print_and_play()` saves a print-and-play file
#' @param filename Filename
#' @param ... Ignored
#' @param size Either `"letter"` or `"A4"`.
#' @param title pdf metadata title.
#' @param crosshairs Character vector, a subset of `c("front", "back")`,
#'   indicating which side(s) of each sheet get crosshairs and cropmarks.
#' @return The filename invisible.  As a side effect creates a pdf file.
#' @export
save_print_and_play <- function(
	filename = "dotaro.pdf",
	...,
	size = c("letter", "a4"),
	title = "Dotaro Deck",
	crosshairs = "back"
) {
	check_dots_empty()
	if (!all(crosshairs %in% c("front", "back"))) {
		abort('`crosshairs` must be a subset of c("front", "back")')
	}
	xmp <- xmpdf::xmp(
		creator = "Trevor L. Davis",
		date_created = "2026",
		spdx_id = "CC-BY-4.0",
		title = title
	)

	envir <- dotaro_decks(round = FALSE, border = FALSE)
	size <- tolower(size)
	size <- match.arg(size)
	width <- switch(size, letter = 8.5, a4 = pnpmisc:::A4_WIDTH)
	height <- switch(size, letter = 11, a4 = pnpmisc:::A4_HEIGHT)

	current_dev <- dev.cur()
	if (current_dev > 1) {
		on.exit(dev.set(current_dev), add = TRUE)
	}

	df <- half_info |>
		filter(.data$top) |>
		select("card", "top") |>
		left_join(full_info, by = c("card", "top")) |>
		arrange(.data$suit, .data$rank)

	layout <- pnpmisc::layout_grid(
		nrow = 3L,
		ncol = 3L,
		width = CARD_WIDTH,
		height = CARD_HEIGHT,
		bleed = 0,
		paper = size,
		orientation = "portrait"
	)

	cairo_pdf(filename, onefile = TRUE, width = width, height = height)

	grid.newpage()
	grid.draw(creditsGrob(xmp))

	# Deliberately blank:
	# keeps the instructions page from ending up printed on the back of the
	# first sheet of cards, so the interleaved front/back pages below start
	# together on a fresh physical sheet under duplex printing.
	grid.newpage()
	grid.text(
		"This page deliberately left blank.",
		gp = gpar(fontfamily = "DejaVu Sans", col = "black", fontsize = 12)
	)

	for (page in 1:12) {
		idx <- seq.int(from = (page - 1L) * 9L + 1L, length.out = 9L)
		dfx <- df[idx, ] |>
			select("suit", "rank", "cfg") |>
			mutate(piece_side = "card_face", x = layout$x, y = layout$y)

		grid.newpage()
		pmap_piece(dfx, default.units = "in", envir = envir)
		if ("front" %in% crosshairs) {
			pnpmisc::grid_add_crosshairs(layout = layout)
			pnpmisc::grid_add_cropmarks(layout = layout, cm_length = unit(1, "in"))
		}

		# Every card shares the same back design, so re-using `dfx`'s own
		# `suit`/`rank`/`cfg` (unused by `card_back`'s grob_fn) at the same
		# `x`/`y` slots keeps this page aligned with the front page above it
		# under a standard "flip on long edge" duplex setting.
		grid.newpage()
		dfx_back <- mutate(dfx, piece_side = "card_back")
		pmap_piece(dfx_back, default.units = "in", envir = envir)
		if ("back" %in% crosshairs) {
			pnpmisc::grid_add_crosshairs(layout = layout)
			pnpmisc::grid_add_cropmarks(layout = layout, cm_length = unit(1, "in"))
		}
	}
	dev.off()

	tmpfile1 <- pnpmisc::pdf_set_xmp(filename, xmp = xmp)
	on.exit(unlink(tmpfile1), add = TRUE)
	tmpfile2 <- pnpmisc::pdf_set_docinfo(tmpfile1, docinfo = xmpdf::as_docinfo(xmp))
	on.exit(unlink(tmpfile2), add = TRUE)
	pnpmisc::pdf_compress(tmpfile2, filename, linearize = TRUE)

	invisible(filename)
}

creditsGrob <- function(xmp = xmpdf::xmp()) {
	# Prevents `marquee::marque_grob()` from leaving open a graphics device
	credits <- c(
		"# Instructions",
		"",
		"* These *Dotaro Deck* cards are provided in a 3x3 layout of bridge sized cards.",
		"* Print double-sided (at actual size, flip on the long edge) preferably on cardstock.",
		"* (Optional) laminate the printed sheets of paper.",
		"* Use the provided crosshairs and cropmarks to cut out the cards.",
		"* (Optional) use a corner rounding tool to round the corners.",
		"* (Optional) place cards into plastic card sleeves.",
		"",
		"# Further information",
		"",
		paste0("* Generated by `dotaro.deck` v", packageDescription("dotaro.deck")$Version),
		"* See https://github.com/trevorld/dotaro.deck for more information.",
		"",
		"# Credits",
		"",
		"* Uses glyphs from the *Dotaro Ranks* and *Dotaro Suits* fonts",
		"",
		"  + https://github.com/trevorld/dotaro.font",
		"  + Dotaro Font License: SIL Open Font License, Version 1.1"
	)

	if (!is.null(xmp$usage_terms)) {
		license <- xmp$usage_terms
	} else {
		license <- "Personal Use Only"
	}
	credits <- c("# License", "", license, "", credits)
	if (!is.null(xmp$title) && !is.null(xmp$attribution_name)) {
		title <- str_glue('*{xmp$title[["x-default"]]}* by {xmp$attribution_name}')
		if (!is.null(xmp$rights)) {
			title <- c(title, "", xmp$rights)
		}
		credits <- c(title, credits)
	}
	credits <- paste(credits, collapse = "\n") |> marquee::marquee_glue(.trim = FALSE)
	# cat(credits, sep = "\n")
	mg <- marquee::marquee_grob(
		credits,
		width = unit(7.0, "in"),
		x = unit(1 / 2, "in"),
		y = unit(1, "npc") - unit(1 / 2, "in"),
		style = credits_style()
	)
	if (is.null(xmp$spdx_id)) {
		grob_cc <- nullGrob()
	} else {
		badge <- piecepackr::spdx_license_list[xmp$spdx_id, "badge"]
		if (is.na(badge)) {
			grob_cc <- nullGrob()
		} else {
			cc_file <- system.file(paste0("extdata/badges/", badge), package = "piecepackr")
			cc_picture <- grImport2::readPicture(cc_file)
			grob_cc <- grImport2::symbolsGrob(
				cc_picture,
				x = unit(0.5, "npc"),
				y = unit(1.00, "in"),
				size = unit(1.5, "in")
			)
		}
	}

	gList(grob_cc, mg)
}

credits_style <- function() {
	if (packageVersion("marquee") >= "1.2.0") {
		# Don't manually set `bullets` to avoid #99
		marquee::classic_style(
			base_size = 10,
			body_font = "Dejavu Sans",
			header_font = "Dejavu Sans",
			lineheight = 1.6,
			margin = marquee::trbl(0, bottom = marquee::rem(0.7))
		) |>
			marquee::modify_style(
				"h1",
				border = NA,
				size = marquee::relative(1.4),
				border_size = marquee::trbl(NULL),
				margin = marquee::trbl(NULL),
				padding = marquee::trbl(NULL)
			) |>
			marquee::modify_style("ul", padding = marquee::trbl(right = marquee::em(1)))
	}
}
